$schema: https://azuremlschemas.azureedge.net/latest/managedOnlineDeployment.schema.json
name: blue
endpoint_name: endpoint1
model: azureml:diabetes_model_oh4ml@latest
code_configuration:
  code: ./scripts
  scoring_script: score.py
environment: 
  conda_file: ./environments/03_conda_env.yml
  image: mcr.microsoft.com/azureml/openmpi3.1.2-ubuntu18.04
instance_type: Standard_DS2_v2
instance_count: 1
